[package]
name = "rust-filebrowser-test"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
either = "1.15.0"
hypertext = "0.6.2"
serde = "1.0.218"
tokio = { version = "1.43.1", features = ["full"] }
